
const myHa = k.jsx)(div,{className:hidden}),!n&&(0,k.jsx)(oO,{animation:`fade-up`,delay:150,children:(0,k.jsxs)(`div`,{className:`mt-20 bg-white rounded-3xl p-8 sm:p-10 border border-slate-200/90 shadow-sm`,children:[(0,k.jsxs)(`div`,{className:`flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-200`,children:[(0,k.jsxs)(`div`,{className:`flex items-center gap-3`,children:[(0,k.jsx)(`div`,{className:`w-12 h-12 rounded-2xl bg-red-50 text-[#d92906] flex items-center justify-center shrink-0`,children:(0,k.jsx)(ii,{className:`w-6 h-6`})}),(0,k.jsxs)(`div`,{children:[(0,k.jsx)(`span`,{className:`text-[11px] font-bold text-[#d92906] uppercase tracking-wider block`,children:`Official Commercial Policy`}),(0,k.jsx)(`h3`,{className:`text-xl sm:text-2xl font-bold font-serif text-slate-900`,children:`Distributor Terms & Commercial Notes`})]})]}),(0,k.jsxs)(`div`,{className:`text-xs text-slate-500 sm:text-right`,children:[(0,k.jsx)(`span`,{className:`font-bold text-slate-700 block`,children:Va.effectiveDate}),(0,k.jsx)(`span`,{className:`text-slate-400`,children:Va.authorizedEntity})]})]}),(0,k.jsx)(`div`,{className:`grid grid-cols-1 md:grid-cols-2 gap-4 pt-6`,children:Va.terms.map(e=>(0,k.jsxs)(`div`,{className:`flex items-start gap-3 p-3.5 rounded-xl bg-slate-50 border border-slate-200/60`,children:[(0,k.jsx)(`span`,{className:`w-6 h-6 rounded-lg bg-[#d92906] text-white text-xs font-bold flex items-center justify-center shrink-0 font-mono`,children:e.code}),(0,k.jsx)(`p`,{className:`text-xs text-slate-700 leading-relaxed font-medium`,children:e.text})]},e.code))}),(0,k.jsxs)(`div`,{className:`mt-6 pt-4 border-t border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs text-slate-500`,children:[(0,k.jsxs)(`div`,{className:`flex items-center gap-2`,children:[(0,k.jsx)(oa,{className:`w-4 h-4 text-[#16a34a]`}),(0,k.jsx)(`span`,{children:`Official Superb MegaCorp Distributor Policy • Sri Saijeet Exports Pvt. Ltd.`})]}),(0,k.jsxs)(`span`,{className:`font-bold text-slate-700`,children:[`Authorised by: `,Va.authorityTitle]})]})]})})];
let i = 'karak-premium';
let o = '';
let m = myHa.filter(e => {
    let t = i === 'all' || e.category === i;
    let n = o.trim().toLowerCase();
    if (!n) return t;
    let r = e.name.toLowerCase().includes(n) || e.sku.toLowerCase().includes(n) || e.packing.toLowerCase().includes(n) || e.categoryName.toLowerCase().includes(n) || e.brand.toLowerCase().includes(n);
    return t && r;
});
console.log("Filtered count for karak-premium:", m.length);
